version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - db_volume:/data/db
    env_file:
      - .env
  srv:
    build: ./
    image: snake:0.0.1
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - mongo
volumes:
  db_volume: